NVARCH=Linux_x86_64; export NVARCH
NVCOMPILERS=/opt/nvidia/hpc_sdk; export NVCOMPILERS
MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/23.7/compilers/man; export MANPATH
PATH=$NVCOMPILERS/$NVARCH/23.7/compilers/bin:$PATH; export PATH
export PATH=$NVCOMPILERS/$NVARCH/23.7/comm_libs/mpi/bin:$PATH
export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/23.7/comm_libs/mpi/man
nvfortran -c -fast -Minfo -acc -cudalib=cusparse -cuda cusolver_mod.f90 
nvfortran -c -fast -Minfo -acc -cudalib=cusparse -cuda main.f90 
nvfortran -o SPsolve cusolver_mod.o main.o -acc -cuda -cudalib=cusolver -L/usr/local/cuda/lib64 -lcusolver -lcusparse